server:
  address: 0.0.0.0:5000 #服务地址

mqtt:
  broker: 127.0.0.1:1883 #mqtt服务端地址
  username: root
  password: root
  topic_to_publish: devices/attributes #发送遥测数据主题
  topic_to_subscribe: plugin/protocol_name/#
  status_topic: device/status
  qos: 0 #qos

http_server:
  address: 0.0.0.0:5001 #http服务地址

thingspanel:
  address: http://127.0.0.1:9999 #thingspanel服务地址


