# configs/config.yaml
server:
  port: 15001
  http_port: 15002
  heartbeatTimeout: 60 # 心跳超时时间(秒)

platform:
  url: "http://47.104.235.67:19999"
  mqtt_broker: "mqtt://47.104.235.67:11883"
  mqtt_username: "root"
  mqtt_password: "root"
  service_identifier: "OG-SZ501"  # 添加服务标识符
  template_secret: "e43823f2-7a91-133b-13d1-612df60fbfdc"  # 模板密钥，用于动态注册

log:
  level: "debug"
  filePath: "logs/app.log"
  enableFile: false  # 是否将日志输出到文件
  maxSize: 100
  maxBackups: 3
  maxAge: 28
  compress: true # 是否压缩日志文件
